### ISSUE TITLE
Serial console prints garbage

### ISSUE THREAD

**Issue by zdravke** [dprinz4/ATmega328PB-Nano-Clone-Bootloader#1]
I uploaded the bootloader to my Nano clone with m328PB from this repo and also installed boards package. Everything seemed fine, but when I upload sketch like this one (interactive version):

https://www.arduinoslovakia.eu/blog/2017/7/16-bitove-rozlisenie-pwm-pre-arduino?lang=en

serial console prints garbage. Blink sketch works fine.

PWM16 sketch works fine with m328P bootloader and same Nano clone board.

**Comment by 0x6470** [comment]
I'm so sorry for my extremely late response I didn't get any notifiction or overlooked it.
However, I will try it and then get back to you.

**Comment by 0x6470** [comment]
![image](https://user-images.githubusercontent.com/36334850/90008877-54dd8000-dc9d-11ea-9d63-143f89f87651.png)
I just tried it and it worked fine.
It could be possible that the blog owner changed something in the mean time, which resolved this error
or that there is an error with your board.
Could you please provide more information?
For example, the output of this sketch: [Atmega_Board_Detector.ino](https://github.com/nickgammon/arduino_sketches/blob/master/Atmega_Board_Detector/Atmega_Board_Detector.ino)
